In [3]:
import numpy as np

In [5]:
a = np.array([1.0,2.0])
print(a)
b = np.array([.5,.5])
c = a+b # Must be same size arrays
print(c)
d = 2.0 * b
print(d)

[1. 2.]
[1.5 2.5]
[1. 1.]


In [8]:
x1 = np.linspace(0,10,6) # linspace() Return an array with evenly spaced numbers over a specified interval.
                        # np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)[source]
x1

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [26]:
xmin = 0.0
xmax = 10.0
xstep = 0.5
x2 = np.arange(xmin, xmax, xstep)
# Return an array with evenly spaced values within a given interval.
print(x2)
# Size vs shape 
print(np.size(x2))
print(np.shape(x2))

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]
20
(20,)


In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.sum(x2)

95.0

In [17]:
np.min(x2)

0.0

In [18]:
np.max(x2)

9.5

In [21]:
# Unit circle values
n = 9
pi = np.pi
t = np.linspace(0,2*pi,n)
print(t)
cost = np.cos(t)
print(cost)
sint = np.sin(t)
print(sint)


[0.         0.78539816 1.57079633 2.35619449 3.14159265 3.92699082
 4.71238898 5.49778714 6.28318531]
[ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -7.07106781e-01
 -1.00000000e+00 -7.07106781e-01 -1.83697020e-16  7.07106781e-01
  1.00000000e+00]
[ 0.00000000e+00  7.07106781e-01  1.00000000e+00  7.07106781e-01
  1.22464680e-16 -7.07106781e-01 -1.00000000e+00 -7.07106781e-01
 -2.44929360e-16]


In [24]:
# 2D array 
aa = np.array([[1,2],[3,4]])
print(aa)
aas = np.shape(aa)
print("size of array:", aas)

[[1 2]
 [3 4]]
size of array (2, 2)


In [27]:
# max() average() apply to all elements in an array
amax = np.max(aa)
print(amax)
aave = np.average(aa)
print(aave)

4
2.5


In [31]:
# Splice
a = np.array([0,1,2,3,4,5,6,7,8,9])
print(np.shape(a))
print("a[0] = ", a[0])
print("a[1:3] = ", a[1:3], "second and third elt")

(10,)
a[0] =  0
a[1:3] =  [1 2] second and third elt


In [33]:
# Vector operations
# Dot Product = x1*x2 + y1*y2 + z1*z2
# Cross product = <y1z2 - z1y2, z1x2 - x1z2, x1y2 - y1x2>
# Matrix multiplication = [3x3][3x1] = 

In [36]:
# Dot product
a1 = np.array([1,2,3])
b1 = np.array([3,4,5])
a1b1 = np.dot(a1,b1)
print(a1b1)

26


In [41]:
b2 = np.array([[1,2,3],[1,2,3],[1,2,3]])
print(a1)
print(b2)
# dot product for two 2D arrays similar to matrix multiplication
print("dot()", np.dot(b2,a1))
print("matmul()", np.matmul(b2,a1))
# cross product
v1 = np.array([1,2,3])
v2 = np.array([3,4,5])
v1xv2 = np.cross(v1,v2)
print("cross()", v1xv2)

[1 2 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]
dot() [14 14 14]
matmul() [14 14 14]
cross() [-2  4 -2]


In [46]:
# Iteration
# For loop


var1 = np.zeros(10)
var1[0] = 1.0
for n in range(1,10):
    var1[n] = -var[n-1] * n
    print(n, var1[n])

TypeError: 'float' object is not subscriptable