# AM10 - Spring 2020

# LAB 02

### Structure of the Lab
The labs for this class are designed to guide you through experimenting with code on your own. The labs have examples and exercises that we will go through during the lab time and a few problems at the end that you have to work on, on your own. We encourage you to collaborate with your peers however each one of you has to submit your own notebook to get credit.


### Learning Goals:

Arrays, array-generating functions and properties (numpy.linspace, numpy.arange, zeros, ones, shape, slicing, sum, ave, max, min), multidimensional arrays, dot product, matrices, matrix-vector multiplication.

Loops: for, while, if/elif/else.

File types, reading/writing file (open, close, read, write).

<hr style="height:2px;color:#000000">

## Python lists v. numpy.arrays
in Python, a list is a collection of elements; all the elements are placed inside a square bracket [ ], separated by commas. A list can have any number of items and they may be of different types (integer, float, string etc.)

An array is a collection of elements of the same type. 


Example of lists:

In [1]:
a = [2, 3, "Ford"] # a is a list containing elements of different types
b = [3., 6., 9.]   # b is a list containing elements of the same type (floating numbers)
                # although it contains elements of the same type, it is not defined as a numpy.array;
                # we cannot perform numerical operations with lists
        
print(type(a), type(b))

<class 'list'> <class 'list'>


In [5]:
# print b/3; what do you think the result will be?

print(b/3)


TypeError: unsupported operand type(s) for /: 'list' and 'int'

Introducing numpy.arrays:

In [4]:
import numpy as np

In [2]:
# defining numpy.arrays

c = np.array([3, 6, 9]) # This is how we define a 1D numpy.array
d = np.array([[3],[6],[9]]) # This is how we define a 2D numpy.array

print(c)
print()
print(d)

[3 6 9]

[[3]
 [6]
 [9]]


### Exercise 0
Print c/3, d/3; what do you think the results will be?



In [4]:
# your code here
print(c/3)
print(d/3)

[1. 2. 3.]
[[1.]
 [2.]
 [3.]]


## Array Operations

It is very important to be able to operate with arrays as needed and access all single elements of arrays for various applications. Python made it very easy to do this.

### Basic Array Algebra

In [5]:
A = np.array([1,3,5,7,9])
B = np.array([0,2,4,6,8])

#D = B[::-1] # presents reverse of array B
print("A =", A)
print("B =", B)
print()

C = A + B 
print ("C =", C)
print ("B-A =", B-A) # element by element deduction
print ("B.A =", np.dot(B,A)) # dot operation of two vectors (We will see more of this later in the lab)

A = [1 3 5 7 9]
B = [0 2 4 6 8]

C = [ 1  5  9 13 17]
B-A = [-1 -1 -1 -1 -1]
B.A = 140


In [6]:
# we can generate arrays by array-generating functions such as numpy.linspace and numpy.arange

E = np.linspace(1,9,5) # this linspace produces an array with length of 5 between 1 and 9 (inclu 9) with elements of equal space
F = np.linspace(0,8,5)

print("E =", E)
print("F =", F)
print ("E-F =", E-F) # element by element deduction
print ("E.F =", np.dot(E,F)) # dot operation of two vectors (We will see more of this later in the lab)

E = [1. 3. 5. 7. 9.]
F = [0. 2. 4. 6. 8.]
E-F = [1. 1. 1. 1. 1.]
E.F = 140.0


In [7]:
# generate arrays by numpy.arange
G = np.arange(1,9,5) # not including 9
H = np.arange(0,8,5)

print("G =", G)
print("H =", H)

G = [1 6]
H = [0 5]


### Accessing elements of an array:

You will soon find out, for any mathematical operation you need to be able to access different portions of an array.

#### Example

In [17]:
numbers_array = np.array([2,5,62,5,42,52,48,5])

print(numbers_array[:-2]) # print all elements except the last two
print(numbers_array[2:6]) # 3rd to 6th
print(numbers_array[2:8:2]) # 3rd to 7th in steps of 2
print(numbers_array[2:]) # beginning from 3rd element to the end
print(numbers_array[5:])  # 6th to end
print(numbers_array[:])   # beginning to end

[ 2  5 62  5 42 52]
[62  5 42 52]
[62 42 48]
[62  5 42 52 48  5]
[52 48  5]
[ 2  5 62  5 42 52 48  5]


In [18]:
# your answer here

print(numbers_array[2:7:2]) # 3rd to 7th in steps of 2
print(numbers_array[2:]) # beginning to 3rd element to the end
print(numbers_array[5:])  # 6th to end
print(numbers_array[:])   # beginning to end

[62 42 48]
[62  5 42 52 48  5]
[52 48  5]
[ 2  5 62  5 42 52 48  5]


### Exercise 1

Make a linspace of (evenly distibuted) numbers from 1 to 20 and print the 4th element to 8th element of the linspace in steps of 2.

In [23]:
#Your code here
a = np.linspace(1,20,num=20)
print(a)
# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)[source]
# Returns num evenly spaced samples, calculated over the interval [start, stop]. The endpoint of the interval can optionally be excluded.
print("Answer:",a[3:8:2])


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]
Answer: [4. 6. 8.]


<hr style="height:2px;color:#000000">

### Defining arrays with 1 row or 1 column and transpose of arrays

Please see the following example carefully:

#### Example:

In [24]:
a = np.array([3,6,9]) # row
a1 = np.array([[3],[6],[9]]) # column
print('a =', a)
print('a1 =', a1)
b= a1.transpose() #This is one way to define transpose of an array
print('b = a1.transpose() =', b)

# getting same result by a1.T
print('a1.T =', a1.T) # attribute of array a1

a = [3 6 9]
a1 = [[3]
 [6]
 [9]]
b = a1.transpose() = [[3 6 9]]
a1.T = [[3 6 9]]


## 2D Arrays

We can create muti-dimensional arrays or matrices using the array module. But for this lab we only focus on 1D and 2D arrays. 2D arrays are also known as matrices.

#### Example :

In [25]:
# Accessing elements of a 2D array:
# 3x4 matrix
A = np.array([[ 1,  4,  5, 12],
 [-5, 8,  9,  0],
 [-6, 7, 11, 19]])

print("A =", A)
print("A[1] =", A[1])      # 2nd row
print("A[1][2] =", A[1][2])   # element of 2nd row, 3rd column 


A = [[ 1  4  5 12]
 [-5  8  9  0]
 [-6  7 11 19]]
A[1] = [-5  8  9  0]
A[1][2] = 9


### Exercise 2

In [31]:
# print the following
# A[1][2] = second row, third column
print("A[1,2] = ",A[1,2])
print("A[1][2] =", A[1][2])   # 3rd element of 2nd row (another notation)
print("A[0][3] =", A[0][3])   # Last element of 1st row
print("A[:,3] =",  A[:,3])  # 4th column of the matrix A

A[1,2] =  9
A[1][2] = 9
A[0][3] = 12
A[:,3] = [12  0 19]


### Matrix Multiplication

In [33]:
A = np.array([[3,6,7], [5,-3,0]])
B = np.array([[1,1],[2,1],[3,-3]])

C = np.dot(A,B) # Matrix multiplication
# row vector dot column vector is the underlying mechanism to produce the element of the resulting matrix
# However, there exist other multiplication schemes, i.e.:

D = A*(B.T)  #Note: * is used for multiplication of corresponding elements of two arrays. B.T is transpose of B

print('A = ', A)
print('B = ', B)
print('C = ', C)
print('D = ', D)

E = np.matmul(A,B)
print('E =', E)

A =  [[ 3  6  7]
 [ 5 -3  0]]
B =  [[ 1  1]
 [ 2  1]
 [ 3 -3]]
C =  [[ 36 -12]
 [ -1   2]]
D =  [[ 3 12 21]
 [ 5 -3  0]]
E = [[ 36 -12]
 [ -1   2]]


### Generating useful arrays (initializing)

In [34]:
a = np.zeros((2,2))   # Create an array of all zeros
print('a =', a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((3,3))    # Create an array of all ones
print('b =', b)              # Prints rows of "[[ 1.  1. 1.]]"

c = np.eye(4)         # Create an identity array of size n
print('c =', c)

a = [[0. 0.]
 [0. 0.]]
b = [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
c = [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Array indexing

Numpy offers several ways to index into arrays.

### Slicing (and modifying) 

Numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3] 

print(a)
print(b)


In [ ]:
# Note: b is a reference of a part of a! 
# Modifying b elements automatically modifies the respective elements of array a (and vice versa)

# In other words: A slice of an array is a view into the same data, so modifying it will modify the original array.

print(a[0,1])   # Prints "2"
b[0,0] =  77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0,1])   # Prints "77"
print(a)

In [ ]:
# How to avoid modifying the original array:

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

b = a[:2, 1:3].copy()   

print(a)
print(b)

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0,1])   # Prints "2"
b[0,0] =  77    # b[0, 0] is the same piece of data as a[0, 1]
print('a[0,1] =', a[0,1])   # Prints "2", because a is not affected by the modification
print(a)


### Reshaping

We can use reshape to change the matrix dimensions.

#### Example:

In [ ]:
a = np.arange(4) #arange would create an array of tandem numbers 
print(np.shape(a))
# print(a.shape)
b = a.reshape(2,2)

c = np.arange(12).reshape(3,4)

print('a=  ', a)
print('b=  ', b)
print('c=  ', c)

In [ ]:
# introducing diagonal
d = b.diagonal()
print(d)

### Exercise 3:

Make array of [0 4 8] by using arange, reshape and diagonal.

In [ ]:
#Your response here


## Matrix Operations

### numpy.dot
If both a and b are 1-D arrays, it is inner product of vectors.<br>
If both a and b are 2-D arrays, it is matrix multiplication. <br>

How each dot product element is calculated: dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
 

Examples of real-life applications: mechanical work is the dot product of force and displacement vectors; power is the dot product of force and velocity.

There are different ways of doing dot product in Python.

In [35]:
# given two arrays a and b:

a = np.array([[5, 1, 3],
            [1, 1, 1],
            [1, 2, 1]])
b = np.array([1, 1, 2])

v = np.dot(a, b)
w = a@b
x = np.inner(a, b) #The inner product is completely different with dot product when dealing with matrices
y = np.tensordot(a, b, axes=1)
z = np.matmul(a, b)

print('v =', v)
print('w =', w)
print('x =', x)
print('y =', y)
print('z =', z)

v = [12  4  5]
w = [12  4  5]
x = [12  4  5]
y = [12  4  5]
z = [12  4  5]


In [37]:
c = a.T           #transpose of an array
print("a= ", a)
print("c= ", c)

a=  [[5 1 3]
 [1 1 1]
 [1 2 1]]
c=  [[5 1 1]
 [1 1 2]
 [3 1 1]]


In [38]:
A= np.inner(a, c) # inner product
print(A)

[[29 12 19]
 [ 7  4  5]
 [ 8  5  6]]


In [ ]:
B= np.dot(a, c)
print(B)

In [ ]:
# outer product

G=np.array([1, 2, 3])
H=np.array([1, 1, 4])
np.outer(G,H)

#### Cross Product

In [ ]:
A=np.array([1, 3, 5])
B=np.array([2, 4, 6])
C=np.cross(A, B)
print('C= ', C)

# Problem 1
Find the angle in degrees between the following vectors: 
$ \vec{a}=3\vec{i}+5\vec{j}-3\vec{k}\, and\, \vec{b}=-\vec{i}+3\vec{k} $.

Reminder: $cos(\Theta)=\frac{\vec{a}.\vec{b}}{|\vec{a}|.|\vec{b}|} $.


Hints: 

(a) in numpy, if y=np.cos(x) then x=np.arccos(y) 

(b) in order to calculate the norm $|\vec{a}|$ you may use $|\vec{a}| = np.sqrt(x^2+y^2+z^2)$, where $\vec{a}=x\vec{i}+y\vec{j}+z\vec{k} \ \ \ \ $        (similarly for $|\vec{b}|$)

In [48]:
# Arrays
a = np.array([3,5,-3])
b = np.array([-1,0,3])
# Dot product of a and b
adotb = np.dot(a,b)
print(adotb)

# Magnitudes of a and b
maga = np.linalg.norm(a)
print("Magnitude of a vector:", maga)
magb = np.linalg.norm(b)
print("Magnitude of b vector:", magb)

# Plug & chug
costheta = adotb / (maga*magb)
angle = np.arccos(costheta)

# Convert
angle = angle * 180 / np.pi
print("degrees = ",angle)

-12
Magnitude of a vector: 6.557438524302
Magnitude of b vector: 3.1622776601683795
degrees =  125.35855428656183


# Problem 2
Find a normal unit vector perpendicular to the following vectors:
$ \vec{a}=3\vec{i}+5\vec{j}-3\vec{k} $, and $ \vec{b}=-\vec{i}+3\vec{k} $.
After finding the normal unit vector, check if the absolute value of it is indeed one (1), and if the dot product of it to each one of the constructing vectors is zero.


In [65]:
# Cross product
acrossb = np.cross(a,b)
print("Normal vector:", acrossb)

# Calculate normal unit vector
acrossb = acrossb / np.linalg.norm(acrossb) # np.linalg.norm() calculates magnitude of a vector

# Magnitude of cross product vector
magcross = np.linalg.norm(acrossb)
print("Magnitude of normal unit vector:", magcross)

# Dot product normal vector and a vector
check = acrossb @ a
print("Dot product of normal vector and a vector:", check)

Normal vector: [15 -6  5]
Magnitude of normal unit vector: 1.0
Dot product of normal vector and a vector: 2.220446049250313e-16


# Problem 3 


The following rotation matrix in three-dimensional space takes any vector $\vec{r}=(x,y,z)$ and rotates it by angle $\theta$ around the $z$-axis.

$$ R(\theta) = \left ( \begin{array}{ccc}
\cos(\theta) & -\sin(\theta) & 0 \\
\sin(\theta) & \cos(\theta)  & 0  \\
0 & 0 & 1 \\ 
\end{array} \right ) $$

(a) Rotate a unit vector in the x-axis by an angle of $\pi$/2.

Hint: the rotated ("new") vector is obtained by the dot product of the rotation matrix $R(\theta)$ with the original vector ($\vec{r}$) as follows: <br>
<br> 
$$\vec{{r_{new}}} = R(\theta).\vec{r}$$
<br>
Note: in the above expression, $\vec{r}$ must be construed as the transpose of the numpy.array representation of the original vector.

(a) Rotate a unit vector in the x-axis by an angle of $\pi$/2.

In [69]:
# Init
ta = np.pi / 2
rx = np.array([1,0,0])

# Rotation matrix R
matrixR = np.array([[np.cos(ta), -np.sin(ta),0],[np.sin(ta), np.cos(ta),0],[0,0,1]])
print("Rotation matrix R = ",matrixR)

# Rotated vector rnew
rnewa = matrixR@(rx.T)
print("Rotated vector = ",rnewa) # should be equal to unit vector in y-axis


Rotation matrix R =  [[ 6.123234e-17 -1.000000e+00  0.000000e+00]
 [ 1.000000e+00  6.123234e-17  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  1.000000e+00]]
Rotated vector =  [6.123234e-17 1.000000e+00 0.000000e+00]


(b) Rotate a unit vector in the x-axis by an angle of $\pi$/4.



In [76]:
# Init
tb = np.pi / 4
rx = np.array([1,0,0])

# Rotation matrix R
matrixR = np.array([[np.cos(tb), -np.sin(tb),0],[np.sin(tb), np.cos(tb),0],[0,0,1]])
print("Rotation matrix R = ",matrixR)

# Rotated vector rnew
rnewb = matrixR@(rx.T)
print("Rotated vector = ",rnewb) # should be equal to unit vector in y-axis

Rotation matrix R =  [[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
Rotated vector =  [0.70710678 0.70710678 0.        ]


(c) Rotate a unit vector in the y-axis by an angle of 2$\pi$.

In [84]:
# Init
tc = 2 * np.pi
ry = np.array([0,1,0])

# Rotation matrix R
matrixR = np.array([[np.cos(tc), -np.sin(tc),0],[np.sin(tc), np.cos(tc),0],[0,0,1]])
print("Rotation matrix R = ",matrixR)

# Rotated vector rnew
rnewc = matrixR@(ry.T)
print("Rotated vector = ",rnewc) # should be equal to unit vector in y-axis

Rotation matrix R =  [[ 1.0000000e+00  2.4492936e-16  0.0000000e+00]
 [-2.4492936e-16  1.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  1.0000000e+00]]
Rotated vector =  [2.4492936e-16 1.0000000e+00 0.0000000e+00]


<hr style="height:2px;color:#000000">

## Loops and ifs

## Numeric Range Loop

The most basic for loop is a simple numeric range statement with start and end values. The exact format varies depending on the language but typically looks something like this:

In [ ]:
for i in range(1,3):
    print('i= ', i)
    
print()

for j in range(0,10,3):
    print('j= ', j)
    
print()
    
for k in range(-10,-100,-30):
    print('k= ', k)


In [ ]:
# Example of printing an array using for loops:

A=np.array([1,2,3,4,5,6])

for i in range(0,4):
    print(A[i])

print()

# another way of printing an array using for loops:

for a in A[0:4]:
    print(a)

print()
    
for a in A:
    print(a)

### Exercise 4

Use a for loop to print the position of a ball, moving with constant speed $v$ = 2 m/s, each second for a total of 10 seconds (starting from 0).

In [ ]:
# Define the "dimension" of the problem (that is, the length of arrays)
ndim = 

# Define the time array
time = 

# velocity
vel = 

# Initialize the position array
pos = 

# remember that position = velocity * time, for this problem

# use a for loop to calculate position values
for i in range(,):
    
    
print('time (s) = \t', time)
print('position (m) = \t', pos)

## While loop

In [ ]:
x = 1
while x<5:
    print(x)
    x += 1

## Nested loops

In [ ]:
for x in range(1,3):
    for y in range(1,3):
        print ("x =", x, "\t y =", y, "\t x + y =", x + y)

## Early exit

In [ ]:
for x in range(1,15):
    print(x)
    if x == 7:
        break

## Conditional loops

In [ ]:
for x in range(1,3):
    print(x)
else:
    print ('Final x = %d' % (x))


## if-elif-else Statements
Python supports the usual logical conditions from mathematics:

Equals: a == b
Not Equals: a != b
Less than: a < b
Less than or equal to: a <= b
Greater than: a > b
Greater than or equal to: a >= b
These conditions can be used in several ways, most commonly in "if statements" and loops.

An "if statement" is written by using the if keyword.

In [ ]:
a = 3
b = 9
if b > a:
  print("b is greater than a")

In [ ]:
a = 15
b = 15
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")

In [ ]:
a = 15
b = 15
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")
else:
  print("a is greater than b")

## Logical statements <i>and</i> & <i>or</i>

In [ ]:
a, b, c = 1, 2, 3
if a > b and c > a:
    print("Both Conditions are True")
elif c > a and b > a:
    print("At least one of the conditions is True")
else:
    print("None of the Conditions are True")

In [ ]:
if a > b or b > a:
    print("At least one of the conditions is True")

<hr style="height:2px;color:#000000">

# File Handling in Python
 

#### Example: 
Create two arrays and write out these arrays in a .csv format. Then, read your file back and print the arrays.  

In [81]:
# Write into csv arrays
a = np.array([0.,1.,2.,3.,4.])
b = np.array([10.,11.,12.,13.,14.])

ab = np.array([a, b])
np.savetxt("outab.txt", ab, fmt="%10.3f")
print(ab.shape)
print(ab)

(2, 5)
[[ 0.  1.  2.  3.  4.]
 [10. 11. 12. 13. 14.]]


In [82]:
# Read arrays from csv

[a_read, b_read] = np.loadtxt("outab.txt")
print(a_read, b_read)
a_read, b_read

[0. 1. 2. 3. 4.] [10. 11. 12. 13. 14.]


(array([0., 1., 2., 3., 4.]), array([10., 11., 12., 13., 14.]))

In [83]:
# another approach to write into csv
# (concatenating the arrays by means of the numpy function np.c_[a,b]):

np.savetxt('outab2.csv', np.c_[a, b], fmt='%10.5f %10.5f', delimiter = ',')

a_read, b_read =np.loadtxt('outab2.csv', unpack = True)
print(np.size(a_read), np.size(b_read))
print(a_read)
print(b_read)


5 5
[0. 1. 2. 3. 4.]
[10. 11. 12. 13. 14.]


# Problem 4

Create three arrays:<br> 
a) x with 10 numbers between 
$[\begin{array}{r}-5.0,& 5.0\\\end{array}]$ <br>
b) $y1=1+ \ x^2$ and <br>
c) $y2=1+\ x^3$. <br>Write out these three arrays in a .csv format file using Python. Then read your file back and print the arrays in this file.

In [3]:
x = np.linspace(-5.0,5.0,10)
y1 = 1 + x**2
y2 = 1 + x**3

'''
print("x:", x)
print("y1:", y1)
print("y2:", y2)
'''

# Write into csv
np.savetxt('output.csv', np.c_[x,y1, y2], fmt='%10.5f %10.5f %10.5f', delimiter = ',')

# Read
a_read, b_read, c_read = np.loadtxt('output.csv', unpack = True)
print(np.size(a_read), np.size(b_read), np.size(c_read))

print(a_read)
print(b_read)
print(c_read)

10 10 10
[-5.      -3.88889 -2.77778 -1.66667 -0.55556  0.55556  1.66667  2.77778
  3.88889  5.     ]
[26.      16.12346  8.71605  3.77778  1.30864  1.30864  3.77778  8.71605
 16.12346 26.     ]
[-124.       -57.81344  -20.43347   -3.62963    0.82853    1.17147
    5.62963   22.43347   59.81344  126.     ]
